version: "3.9"
services:
  web:
    container_name: test
    image: quanglongtran/php:81
    ports:
      - "3:80"
    volumes:
      - /programing/laravel/test:/usr/share/nginx/html
      - ./nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/share/nginx/html
    networks:
      - db_default
networks:
  db_default:
    external: true
